export enum AuthTypes {
  // вхід
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",
  // вихід
  LOGOUT_REQUEST = "LOGOUT_REQUEST",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
  LOGOUT_FAILURE = "LOGOUT_FAILURE",
  // оновлення токена
  REFRESH_TOKEN_REQUEST = "REFRESH_TOKEN_REQUEST",
  REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILURE = "REFRESH_TOKEN_FAILURE",
  // інформації про користувача
  GET_USER_INFO_REQUEST = "GET_USER_INFO_REQUEST",
  GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS",
  GET_USER_INFO_FAILURE = "GET_USER_INFO_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
