export enum BookingTypes {
  // завантаження заявок
  LOAD_BOOKING_REQUEST = "LOAD_BOOKING_REQUEST",
  LOAD_BOOKING_SUCCESS = "LOAD_BOOKING_SUCCESS",
  LOAD_BOOKING_FAILURE = "LOAD_BOOKING_FAILURE",
  // додавання нової заявки
  ADD_BOOKING_REQUEST = "ADD_BOOKING_REQUEST",
  ADD_BOOKING_SUCCESS = "ADD_BOOKING_SUCCESS",
  ADD_BOOKING_FAILURE = "ADD_BOOKING_FAILURE",
  // зміна заявки
  UPDATE_BOOKING_REQUEST = "UPDATE_BOOKING_REQUEST",
  UPDATE_BOOKING_SUCCESS = "UPDATE_BOOKING_SUCCESS",
  UPDATE_BOOKING_FAILURE = "UPDATE_BOOKING_FAILURE",
  // видалення заявки
  DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST",
  DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS",
  DELETE_BOOKING_FAILURE = "DELETE_BOOKING_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
