export enum CategoriesTypes {
  // завантаження категорій
  LOAD_CATEGORIES_REQUEST = "LOAD_CATEGORIES_REQUEST",
  LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS",
  LOAD_CATEGORIES_FAILURE = "LOAD_CATEGORIES_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
