export enum EmployeesTypes {
  // завантаження співробітників
  LOAD_EMPLOYEES_REQUEST = "LOAD_EMPLOYEES_REQUEST",
  LOAD_EMPLOYEES_SUCCESS = "LOAD_EMPLOYEES_SUCCESS",
  LOAD_EMPLOYEES_FAILURE = "LOAD_EMPLOYEES_FAILURE",
  // схвалення заявки співробітника
  APPROVE_EMPLOYEE_REQUEST = "APPROVE_EMPLOYEE_REQUEST",
  APPROVE_EMPLOYEE_SUCCESS = "APPROVE_EMPLOYEE_SUCCESS",
  APPROVE_EMPLOYEE_FAILURE = "APPROVE_EMPLOYEE_FAILURE",
  // додавання нового співробітника
  ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST",
  ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE",
  // зміна співробітника
  UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST",
  UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_FAILURE = "UPDATE_EMPLOYEE_FAILURE",
  // видалення співробітника
  DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST",
  DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_FAILURE = "DELETE_EMPLOYEE_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
