export enum EmployeeServicesTypes {
  // завантаження послуг співробітників
  LOAD_EMPLOYEE_SERVICES_REQUEST = "LOAD_EMPLOYEE_SERVICES_REQUEST",
  LOAD_EMPLOYEE_SERVICES_SUCCESS = "LOAD_EMPLOYEE_SERVICES_SUCCESS",
  LOAD_EMPLOYEE_SERVICES_FAILURE = "LOAD_EMPLOYEE_SERVICES_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
