export enum RegionsTypes {
  // завантаження регіонів
  LOAD_REGIONS_REQUEST = "LOAD_REGIONS_REQUEST",
  LOAD_REGIONS_SUCCESS = "LOAD_REGIONS_SUCCESS",
  LOAD_REGIONS_FAILURE = "LOAD_REGIONS_FAILURE",
  // додавання нового регіону
  ADD_REGION_REQUEST = "ADD_REGION_REQUEST",
  ADD_REGION_SUCCESS = "ADD_REGION_SUCCESS",
  ADD_REGION_FAILURE = "ADD_REGION_FAILURE",
  // зміна регіону
  UPDATE_REGION_REQUEST = "UPDATE_REGION_REQUEST",
  UPDATE_REGION_SUCCESS = "UPDATE_REGION_SUCCESS",
  UPDATE_REGION_FAILURE = "UPDATE_REGION_FAILURE",
  // видалення регіону
  DELETE_REGION_REQUEST = "DELETE_REGION_REQUEST",
  DELETE_REGION_SUCCESS = "DELETE_REGION_SUCCESS",
  DELETE_REGION_FAILURE = "DELETE_REGION_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
