export enum ServiceTypesTypes {
  // завантаження типів послуги
  LOAD_SERVICE_TYPES_REQUEST = "LOAD_SERVICE_TYPES_REQUEST",
  LOAD_SERVICE_TYPES_SUCCESS = "LOAD_SERVICE_TYPES_SUCCESS",
  LOAD_SERVICE_TYPES_FAILURE = "LOAD_SERVICE_TYPES_FAILURE",
  // скидання даних
  RESET_DATA = "RESET_DATA",
}
